name: Make docker images
on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
    inputs:
      tag:
        description: 'Docker image tag (e.g., k8s-test, custom-tag)'
        required: false
        default: 'manual-build'
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 5
      matrix:
        include:
          # ghcr.io/henrygd/beszel
          - image: ghcr.io/eleboucher/beszel
            dockerfile: ./internal/dockerfile_hub
            registry: ghcr.io
            username: ${{ github.actor }}
            password_secret: GITHUB_TOKEN
            tags: |
              type=raw,value=edge
              type=semver,pattern={{version}}
              type=semver,pattern={{major}}.{{minor}}
              type=semver,pattern={{major}}
              type=raw,value={{sha}},enable=${{ github.ref_type != 'tag' && github.event_name != 'workflow_dispatch' }}
              type=raw,value=${{ github.event.inputs.tag || 'manual-build' }},enable=${{ github.event_name == 'workflow_dispatch' }}
          # ghcr.io/henrygd/beszel-agent
          - image: ghcr.io/eleboucher/beszel-agent
            dockerfile: ./internal/dockerfile_agent
            registry: ghcr.io
            username: ${{ github.actor }}
            password_secret: GITHUB_TOKEN
            tags: |
              type=raw,value=edge
              type=raw,value=latest,enable=${{ github.ref_type == 'tag' }}
              type=semver,pattern={{version}}
              type=semver,pattern={{major}}.{{minor}}
              type=semver,pattern={{major}}
              type=raw,value={{sha}},enable=${{ github.ref_type != 'tag' && github.event_name != 'workflow_dispatch' }}
              type=raw,value=${{ github.event.inputs.tag || 'manual-build' }},enable=${{ github.event_name == 'workflow_dispatch' }}
          # ghcr.io/henrygd/beszel-agent-nvidia
          - image: ghcr.io/eleboucher/beszel-agent-nvidia
            dockerfile: ./internal/dockerfile_agent_nvidia
            platforms: linux/amd64
            registry: ghcr.io
            username: ${{ github.actor }}
            password_secret: GITHUB_TOKEN
            tags: |
              type=raw,value=edge
              type=semver,pattern={{version}}
              type=semver,pattern={{major}}.{{minor}}
              type=semver,pattern={{major}}
              type=raw,value={{sha}},enable=${{ github.ref_type != 'tag' && github.event_name != 'workflow_dispatch' }}
              type=raw,value=${{ github.event.inputs.tag || 'manual-build' }},enable=${{ github.event_name == 'workflow_dispatch' }}
          # ghcr.io/henrygd/beszel-agent-intel
          - image: ghcr.io/eleboucher/beszel-agent-intel
            dockerfile: ./internal/dockerfile_agent_intel
            platforms: linux/amd64
            registry: ghcr.io
            username: ${{ github.actor }}
            password_secret: GITHUB_TOKEN
            tags: |
              type=raw,value=edge
              type=semver,pattern={{version}}
              type=semver,pattern={{major}}.{{minor}}
              type=semver,pattern={{major}}
              type=raw,value={{sha}},enable=${{ github.ref_type != 'tag' && github.event_name != 'workflow_dispatch' }}
              type=raw,value=${{ github.event.inputs.tag || 'manual-build' }},enable=${{ github.event_name == 'workflow_dispatch' }}
          # ghcr.io/henrygd/beszel-agent:alpine
          - image: ghcr.io/eleboucher/beszel-agent
            dockerfile: ./internal/dockerfile_agent_alpine
            registry: ghcr.io
            username: ${{ github.actor }}
            password_secret: GITHUB_TOKEN
            tags: |
              type=raw,value=alpine
              type=semver,pattern={{version}}-alpine
              type=semver,pattern={{major}}.{{minor}}-alpine
              type=semver,pattern={{major}}-alpine
              type=raw,value=${{ github.event.inputs.tag || 'manual-build' }}-alpine,enable=${{ github.event_name == 'workflow_dispatch' }}
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up bun
        uses: oven-sh/setup-bun@v2
      - name: Install dependencies
        run: bun install --no-save --cwd ./internal/site
      - name: Build site
        run: bun run --cwd ./internal/site build
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Docker metadata
        id: metadata
        uses: docker/metadata-action@v5
        with:
          images: ${{ matrix.image }}
          tags: ${{ matrix.tags }}
      # Login to GitHub Container Registry
      - name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ matrix.registry }}
          username: ${{ matrix.username }}
          password: ${{ secrets[matrix.password_secret] }}
      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./
          file: ${{ matrix.dockerfile }}
          platforms: ${{ matrix.platforms || 'linux/amd64,linux/arm64,linux/arm/v7' }}
          push: ${{ github.ref_type == 'tag' || github.event_name == 'workflow_dispatch' }}
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
